name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install and Build ğŸ¬
        run: |
          npm install
          npm run build
          
      - name: Zip ğŸ“¥
        uses: montudor/action-zip@v1
        working-directory: build
        with:
          args: zip -qq -r ../build.zip .

      - name: Deploy ğŸš€
        uses: JantHsueh/upload-file-action@master
        with:
          url: ${{ secrets.KIJYA_URL }}
          forms: '{"password":"${{ secrets.KIJYA_PASS }}","path":"${{ secrets.KIJYA_PATH }}"}'
          fileForms: '{"file":"build.zip"}'
